### ISSUE TITLE
Circular Dependency

### ISSUE THREAD

**Issue by tillchen** [iuliacornea99/SE-CourseInfo#10]
`Game -> Order -> PlayerEvent -> Player -> Game` creates a circular dependency. We should probably avoid it? @iuliacornea99 @rahulbshrestha

**Comment by drishti-m** [comment]
It is possible to avoid this issue with forward declaration. Since, we would need Game* in Player, and Player in Game, to implement according to current class diagram-> Update 3, I don't think we can avoid this.

**Comment by tillchen** [comment]
@ohwhatafool That's a good point! I did resolve it using forward declarations. If this is a must, maybe we can at least make them loosely coupled instead?
